# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Daeseda' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Daeseda
  # HTTP 네트워킹 라이브러리
  pod 'Alamofire', '~> 5.7'
  pod 'TossPayments'

end
